[config.wallpaper]
set = true
command = "awww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "144", "--transition-duration", "2", "--transition-bezier", ".43,1.19,1,.4"]

[config.colors]
color_mode = "dark"
accent = "primary"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'kill -SIGUSR1 $(pgrep kitty)'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar; waybar & disown'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'pkill swaync; swaync & disown'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.config/tmux/colors.conf'
post_hook = 'tmux source-file ~/.config/tmux/tmux.conf'

[templates.code]
input_path = "~/.config/matugen/templates/code.jsonc"
output_path = "~/.config/nvim/colors/code-colors.jsonc"
post_hook = "pkill -SIGUSR1 nvim"

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.rmpc]
input_path = '~/.config/matugen/templates/rmpc.ron'
output_path = '~/.config/rmpc/themes/matugen.ron'

[templates.heroic]
input_path = '~/.config/matugen/templates/heroic.css'
output_path = '~/.config/heroic/themes/matugen.css'

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = ['~/.config/spicetify/Themes/Sleek/color.ini', '~/.config/spicetify/Themes/text/color.ini']
post_hook = 'spicetify apply -n'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.obs]
input_path = '~/.config/matugen/templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Obsidian Vault/.obsidian/snippets/matugen.css'

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'adwaita-steam-gtk -i'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.firefox]
input_path = '~/.config/matugen/templates/firefox.css'
output_path = '~/.config/mozilla/firefox/colors.css'
