[matugen]
; text pattern
main               = 0e1415
accent             = 80d4dc
accent-active      = 9df0f8
accent-inactive    = 343a3b
banner             = 80d4dc
border-active      = 80d4dc
border-inactive    = 899393
header             = 80d4dc
highlight          = 80d4dc
notification       = 0e1415
notification-error = ffb4ab
text               = dee4e4
subtext            = bec8c9
; sleek pattern
button             = 80d4dc
button-secondary   = b1cbce
button-active      = 9df0f8
button-disabled    = 343a3b
sidebar            = 0e1415
player             = 0e1415
card               = 343a3b
main-secondary     = 343a3b
misc               = b7c7ea
shadow             = 000000
nav-active-text    = 80d4dc
nav-active         = 80d4dc
tab-active         = 0e1415
play-button        = 80d4dc
playback-bar       = 9df0f8
