---
- name: Install AUR packages
  kewlfft.aur.aur:
    use: paru
    name:
      - zen-browser-bin
      - vesktop-bin
      - localsend-bin
      - spotify
      - spicetify-cli
      - adwsteamgtk
      - lsfg-vk-git
      - heroic-games-launcher-bin
      - protonplus
      - bibata-cursor-theme
